[package]
name = "beamdump"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
beam_file = "0.3"
byteorder = "1"
clap = { version = "3", features = ["derive"] }
eetf = "0.8"
